name: Manual-Trigger-To-Extract-From-Dev-APIM-Instance
run-name: Manual-Trigger-To-Extract-From-Dev-APIM-Instance
#martin francis kallukalam
on:
  workflow_dispatch:
    inputs:
      EXTRACTOR_OPTION:
        description: 'Choose whether to extract all OR selected artifacts from extractor config file'     
        required: true
        type: choice
        options:
        - 'Extract Selected APIM Artifacts'
        - 'Extract All APIM Artifacts'
      API_SPECIFICATION_FORMAT:
        description: 'API specification format to extract the API spec'     
        required: true
        type: choice
        options:
        - OpenAPIV3Yaml 
        - OpenAPIV3Json
        - OpenAPIV2Yaml
        - OpenAPIV2Json
        default: OpenAPIV3Yaml
      REFERENCE_NUMBER:
        description: 'Reference(ticket) number to include in the title of PR.'     
        required: true
        type: string
        default: 'RITM100000'
      BRANCH_TO_EXTRACT_ARTIFACTS:
        description: 'Enter the branch where artifacts should be extracted from APIM.'     
        required: true
        type: choice
        default: "working"
        options:
        - "working"
permissions:
  contents: read
  id-token: write
concurrency:
 group: extract-from-dev-apim-instance
 cancel-in-progress: false
env:
  APIOPS_WORKFLOW_REPO: 'martin2176/ecs-apim-workflows'
  PULL_REQUEST_LABEL: ticket-${{ github.event.inputs.REFERENCE_NUMBER }}
  BASE_BRANCH_FOR_PR: 'main'
  HEAD_BRANCH_FOR_PR: ${{ github.event.inputs.BRANCH_TO_EXTRACT_ARTIFACTS }}
jobs:
    Set-Variables-to-Extract-Artifacts:
     name: Set-Variables-to-Extract-Artifacts
     runs-on: ubuntu-latest
     steps:
      - name: set-variables
        id: set-variables
        run: |
         echo "BASE_BRANCH_FOR_PR=${{ env.BASE_BRANCH_FOR_PR }}" >> "$GITHUB_OUTPUT"
         echo "HEAD_BRANCH_FOR_PR=${{ env.HEAD_BRANCH_FOR_PR }}" >> "$GITHUB_OUTPUT"
     outputs:
      BASE_BRANCH_FOR_PR: ${{ steps.set-variables.outputs.BASE_BRANCH_FOR_PR }}
      HEAD_BRANCH_FOR_PR: ${{ steps.set-variables.outputs.HEAD_BRANCH_FOR_PR }}
    Print-User-Selections:
     needs: Set-Variables-to-Extract-Artifacts
     name: Print-User-Selections
     runs-on: ubuntu-latest
     steps:
      - name: print-user-selections
        id: print-user-selections
        run: |
         echo "Extractor Options: ${{ inputs.EXTRACTOR_OPTION }}"
         echo "API Specification Format: ${{ inputs.API_SPECIFICATION_FORMAT}}"
         echo "Reference ticket#: ${{ inputs.REFERENCE_NUMBER }}"
         echo "Branch to extract artifacts to: ${{ inputs.BRANCH_TO_EXTRACT_ARTIFACTS }}"
         echo "PR Label: ticket-${{ github.event.inputs.REFERENCE_NUMBER }}"
         echo "Base Branch for PR: ${{ needs.Set-Variables-to-Extract-Artifacts.outputs.BASE_BRANCH_FOR_PR }}"
         echo "Head Branch for PR: ${{ needs.Set-Variables-to-Extract-Artifacts.outputs.HEAD_BRANCH_FOR_PR }}"
    Extract-from-Dev-APIM-Instance:
     needs: Set-Variables-to-Extract-Artifacts
     if: ${{ !always() }}
     uses: martin2176/ecs-apim-workflows/.github/workflows/extract-from-dev-apim.yml@main
     with:
      EXTRACTOR_OPTION: ${{ inputs.EXTRACTOR_OPTION }} 
      API_SPECIFICATION_FORMAT: ${{ inputs.API_SPECIFICATION_FORMAT }} 
      REFERENCE_NUMBER: ${{ inputs.REFERENCE_NUMBER }} 
      REFTOCHECKOUTFOR_EXTRACTORCONFIG: dev
      PULL_REQUEST_LABEL: ticket-${{ github.event.inputs.REFERENCE_NUMBER }}
      BASE_BRANCH_FOR_PR: ${{ needs.Set-Variables-to-Extract-Artifacts.outputs.BASE_BRANCH_FOR_PR }}
      HEAD_BRANCH_FOR_PR: ${{ needs.Set-Variables-to-Extract-Artifacts.outputs.HEAD_BRANCH_FOR_PR }}
      CONFIGURATION_YAML_PATH: configuration-extractor-dev.yml
     secrets: inherit