name: Manual-Trigger-To-Extract-From-Dev-APIM-Instance
run-name: Manual-Trigger-To-Extract-From-Dev-APIM-Instance
#martin f kallukalam
on:
  workflow_dispatch:
    inputs:
      EXTRACTOR_OPTION:
        description: 'Choose whether to extract all OR selected artifacts from extractor config file'     
        required: true
        type: choice
        options:
        - 'Extract Selected APIM Artifacts'
        - 'Extract All APIM Artifacts'
      API_SPECIFICATION_FORMAT:
        description: 'API specification format to extract the API spec'     
        required: true
        type: choice
        options:
        - OpenAPIV3Yaml 
        - OpenAPIV3Json
        - OpenAPIV2Yaml
        - OpenAPIV2Json
        default: OpenAPIV3Yaml
      REFERENCE_NUMBER:
        description: 'Reference(ticket) number to include in the title of PR.'     
        required: true
        type: string
        default: 'RITM100000'
      BRANCH_TO_EXTRACT_ARTIFACTS:
        type: string
        default: 'artifacts'
        description: 'Enter the branch where artifacts should be extracted from APIM.' 

permissions:
  contents: read
  id-token: write
concurrency:
 group: extract-from-dev-apim-instance
 cancel-in-progress: false
env:
  APIOPS_WORKFLOW_REPO: 'martin2176/ecs-apim-workflows'
  REFTOCHECKOUTFOR_EXTRACTORCONFIG: dev
  PULL_REQUEST_LABEL: ticket-${{ github.event.inputs.REFERENCE_NUMBER }}
  BASE_BRANCH_FOR_PR: ${{ github.event.inputs.BRANCH_TO_EXTRACT_ARTIFACTS }}
  HEAD_BRANCH_FOR_PR: 'working'
  BRANCH_TO_EXTRACT_ARTIFACTS: ${{ github.event.inputs.BRANCH_TO_EXTRACT_ARTIFACTS }}
  PR_REQUIRED: ${{ github.event.inputs.BRANCH_TO_EXTRACT_ARTIFACTS == 'artifacts' && 'YES' || 'NO' }}
jobs:
    Print-User-Selections:
     name: Print-User-Selections
     runs-on: ubuntu-latest
     needs: Set-CommitID-to-Publish-Artifacts
     steps:
      - name: print-user-selections
        id: print-user-selections
        run: |
         echo "Extractor Options: ${{ inputs.EXTRACTOR_OPTION }}"
         echo "API Specification Format: ${{ inputs.API_SPECIFICATION_FORMAT}}"
         echo "Reference ticket#: ${{ inputs.REFERENCE_NUMBER }}"
         echo "Branch to extract artifacts to: ${{ inputs.BRANCH_TO_EXTRACT_ARTIFACTS }}"
         echo "PR Label: ${{ env.PULL_REQUEST_LABEL }}"
         echo "Base Branch for PR: ${{ env.BASE_BRANCH_FOR_PR }}"
         echo "Head Branch for PR: ${{ env.HEAD_BRANCH_FOR_PR }}"
         echo "PR Required?: ${{ env.PR_REQUIRED }}"

    Extract-from-Dev-APIM-Instance:
     if: ${{ !always() }}
     name: Extract-from-Dev-APIM-Instance
     needs: Print-User-Selections
     uses: martin2176/ecs-apim-workflows/.github/workflows/reusableworkflow.yml@main
     with:
      EXTRACTOR_OPTION: ${{ inputs.EXTRACTOR_OPTION }} 
      API_SPECIFICATION_FORMAT: ${{ inputs.API_SPECIFICATION_FORMAT }} 
      REFERENCE_NUMBER: ${{ inputs.REFERENCE_NUMBER }} 
      BRANCH_TO_EXTRACT_ARTIFACTS: ${{ needs.Set-CommitID-to-Publish-Artifacts.outputs.COMMITID }}
      REFTOCHECKOUTFOR_EXTRACTORCONFIG: ${{ needs.Set-CommitID-to-Publish-Artifacts.outputs.PUBLISH_ARTIFACTS_CHOICE }}
      PULL_REQUEST_LABEL: apimartifacts
      BASE_BRANCH_FOR_PR: configuration-publisher-dev.yml
      HEAD_BRANCH_FOR_PR: dev
      PR_REQUIRED: ${{ inputs.BRANCH_TO_DEPLOY_FROM }}      
     secrets: inherit