name: Manual-Trigger-To-Publish-to-Dev-APIM
run-name: Manual-Trigger-To-Publish-to-Dev-APIM
on:
   workflow_dispatch:
    inputs:
     PUBLISH_ARTIFACTS_CHOICE:
      description: 'Choose from list of option(s)"'
      required: true
      type: choice
      default: "publish-delta-artifacts-in-latest-commit"
      options:
       - "publish-delta-artifacts-in-latest-commit"
       - "publish-delta-artifacts-in-specific-commit"
       - "publish-all-artifacts-in-repo"
     BRANCH_TO_DEPLOY_FROM:
      description: 'Branch to deploy APIM artifacts from.'     
      required: true
      type: choice
      default: "main"
      options:
       - "main"
     REFTOCHECKOUTFOR_ARTIFACTS:
      description: 'Enter specific Commit ID (long commit) in developer branch to look for artifacts.Default to the latest commit'     
      required: true
      type: string
      default: "latest commit"

permissions:
  contents: read
  id-token: write
concurrency:
 group: publish-to-dev-apim-instance
 cancel-in-progress: false
env:
  APIOPS_WORKFLOW_REPO: 'martin2176/ecs-apim-workflows'
  
jobs:
    Set-CommitID-to-Publish-Artifacts:
     if:  ${{ github.event_name == 'workflow_dispatch' }}
     name: Set-CommitID-to-Publish-Artifacts
     runs-on: ubuntu-latest
     steps:
      - name: checkout-developer-branch
        id: checkout-developer-branch
        uses: actions/checkout@v4
        with:
         ref: '${{ inputs.BRANCH_TO_DEPLOY_FROM }}'
         fetch-tags: 'false'
         fetch-depth: 15
      - name: set-commitid-on-manual-run-to-latest-commit
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.PUBLISH_ARTIFACTS_CHOICE == 'publish-delta-artifacts-in-latest-commit' }}
        id: set-commitid-on-manual-run-to-latest-commit
        run: echo "COMMITID=$(git rev-parse HEAD)" >> $GITHUB_ENV
      - name: set-commitid-on-manual-run-to-specific-commit
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.PUBLISH_ARTIFACTS_CHOICE == 'publish-delta-artifacts-in-specific-commit' }}
        id: set-commitid-on-manual-run-to-specific-commit
        run: echo "COMMITID=${{ inputs.REFTOCHECKOUTFOR_ARTIFACTS }}" >> $GITHUB_ENV
      - name: set-commitid-on-manual-run-to-null-commit
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.PUBLISH_ARTIFACTS_CHOICE == 'publish-all-artifacts-in-repo' }}
        id: set-commitid-on-manual-run-to-null-commit
        run: echo "COMMITID=${{ inputs.BRANCH_TO_DEPLOY_FROM }}" >> $GITHUB_ENV
      - name: set-commitid
        id: set-commitid
        run: |
         echo "COMMITID=${COMMITID}" >> "$GITHUB_OUTPUT"
         echo "PUBLISH_ARTIFACTS_CHOICE=${{ inputs.PUBLISH_ARTIFACTS_CHOICE }}" >> "$GITHUB_OUTPUT"
     outputs:
      COMMITID: ${{ steps.set-commitid.outputs.COMMITID }}
      PUBLISH_ARTIFACTS_CHOICE: ${{ steps.set-commitid.outputs.PUBLISH_ARTIFACTS_CHOICE }}
    
    Print-User-Selections:
     name: Print-User-Selections
     runs-on: ubuntu-latest
     needs: Set-CommitID-to-Publish-Artifacts
     steps:
      - name: print-user-selections
        id: print-user-selections
        run: |
         echo "ref(commitid) to checkout artifacts(commitid of branch name means everything in the branch): ${{ needs.Set-CommitID-to-Publish-Artifacts.outputs.COMMITID}}"
         echo "publish artifacts choice: ${{ needs.Set-CommitID-to-Publish-Artifacts.outputs.PUBLISH_ARTIFACTS_CHOICE}}"
         echo "branch to deploy artifacts from: ${{ inputs.BRANCH_TO_DEPLOY_FROM }}"

    Deploy-to-Dev-APIM-Instance:
     if: ${{ always() }}
     name: Deploy-to-Dev-APIM-Instance
     needs: Set-CommitID-to-Publish-Artifacts
     uses: martin2176/ecs-apim-workflows/.github/workflows/publish-to-dev-apim.yml@main
     with:
      COMMITID: ${{ needs.Set-CommitID-to-Publish-Artifacts.outputs.COMMITID }}
      PUBLISH_ARTIFACTS_CHOICE: ${{ needs.Set-CommitID-to-Publish-Artifacts.outputs.PUBLISH_ARTIFACTS_CHOICE }}
      API_MANAGEMENT_SERVICE_OUTPUT_FOLDER_PATH: apimartifacts
      CONFIGURATION_YAML_PATH: configuration-publisher-dev.yml
      API_MANAGEMENT_ENVIRONMENT: dev
      BRANCH_TO_DEPLOY_FROM: ${{ inputs.BRANCH_TO_DEPLOY_FROM }}      
     secrets: inherit
    Call-to-ReUsableWorkFlow:
     if: ${{ !always() }}
     needs: Set-CommitID-to-Publish-Artifacts
     uses: martin2176/ecs-apim-workflows/.github/workflows/reusableworkflow.yml@main
     with:
      COMMITID: ${{ needs.Set-CommitID-to-Publish-Artifacts.outputs.COMMITID }}
      PUBLISH_ARTIFACTS_CHOICE: ${{ needs.Set-CommitID-to-Publish-Artifacts.outputs.PUBLISH_ARTIFACTS_CHOICE }}
      API_MANAGEMENT_SERVICE_OUTPUT_FOLDER_PATH: apimartifacts
      CONFIGURATION_YAML_PATH: configuration-publisher-dev.yml
      API_MANAGEMENT_ENVIRONMENT: dev
      BRANCH_TO_DEPLOY_FROM: ${{ inputs.BRANCH_TO_DEPLOY_FROM }}
     secrets:
      inherit