name: PRMerge-Trigger-To-Publish-to-Dev-APIM
run-name: PRMerge-Trigger-To-Publish-to-Dev-APIM
#author martin francis kallukalam
on:
   pull_request:
    branches: [main]
    types: [closed]
    paths: 
     - 'apimartifacts/**'
concurrency:
 group: prmeerge-trigger-to-publish-to-dev-apim
 cancel-in-progress: false
jobs:
    Prerequisite-Check-and-Tag-Commit:
     if:  ${{ (github.event_name == 'pull_request' && github.event.pull_request.merged == true) }}
     name: Prerequisite-Check-and-Tag-Commit
     uses: martin2176/ecs-apim-workflows/.github/workflows/prereq-check-and-tag-commit.yml@main
     with:
      PR_NUMBER: ${{ github.event.pull_request.number }}
      PR_MILESTONE_NUMBER: ${{ github.event.pull_request.milestone.number }}
      PR_MILESTONE_TITLE: ${{ github.event.pull_request.milestone.title }}
      PR_MERGE_COMMIT_SHA: ${{ github.event.pull_request.merge_commit_sha }}
      PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
      PR_STATE: ${{ github.event.pull_request.state }}
      PR_BASE_REF: ${{ github.event.pull_request.base.ref }}
      PR_HEAD_REF: ${{ github.event.pull_request.head.ref }}