name: PR-Without-MileStone-Block-Merging
run-name: PR-Without-MileStone-Block-Merging
#author martin francis kallukalam
on:
   pull_request:
    branches:
     - main
    types: [opened, reopened, edited, milestoned, demilestoned,labeled,unlabeled]
   workflow_call:
concurrency:
 group: prblock-without-milestone
 cancel-in-progress: true
permissions:
  contents: read
jobs:
    GHA-Status-Check-For-MileStone:
     name: GHA-Status-Check-For-MileStone
     runs-on: ubuntu-latest
     steps:
      - name: printoutput
        run: |
         echo "________________"
         echo "${{ github.event.pull_request.milestone }}"
         echo "${{ github.event_name }}"
         echo "________________"

      - name: check-milestone-on-manually-trigerred-pr
        if: ${{ (github.event.pull_request.milestone == null && github.event_name == 'pull_request') }}
        run: |
          echo "PR: ${{ github.event.pull_request.number }} does not have a milestone attached."
          echo "Close and reopen PR with a milestone or attach a milestone to PR.Exiting."
          echo "PR: ${{ github.event.pull_request.number }} does not have a milestone attached." >> $GITHUB_STEP_SUMMARY
          echo "Close and reopen PR with a milestone or attach a milestone to PR.Exiting." >> $GITHUB_STEP_SUMMARY
          exit 1
      - name: check-milestone-on-workflow-trigerred-pr
        if: ${{ github.event_name == 'workflow_call' }}
        run: |
          echo "PR created with milestone."