name: TestTeams
run-name: TestTeams
#martin francis kallukalam
on:
  workflow_dispatch:
jobs:
    messageteams:
     uses: martin2176/ecs-apim-workflows/.github/workflows/msteamsnotification.yml@main
     with:
      TITLE: "main"
      SUBTITLE: "sub"
      CHANNEL_NAME: "PR_APPROVAL_CHANNEL"
      MESSAGE_TITLE: "hellothere"
      MESSAGE_BODY: "messagebody"